<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class JobCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name_en' => 'required',
            'name_vi' => 'required',
            'name_jp' => 'required',
        ];
    }

    public function attributes()
    {
        return [
            'name_en' => trans('job_category.name_en'),
            'name_vi' => trans('job_category.name_vi'),
            'name_jp' => trans('job_category.name_jp'),
        ]; // TODO: Change the autogenerated stub
    }
}
